# Generated by Django 6.0.1 on 2026-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='file_extension',
            field=models.CharField(default='.txt', max_length=10),
        ),
    ]
